FROM mongo-express

# ENV ME_CONFIG_MONGODB_ADMINUSERNAME username
# ENV ME_CONFIG_MONGODB_ADMINPASSWORD password
ENV ME_CONFIG_BASICAUTH_USERNAME username
ENV ME_CONFIG_BASICAUTH_PASSWORD password
ENV ME_CONFIG_MONGODB_URL mongodb://username:password@mongo:27017/

EXPOSE 8081