FROM mongo-express

ENV ME_CONFIG_BASICAUTH_USERNAME username
ENV ME_CONFIG_BASICAUTH_PASSWORD password

ARG MONGO_PRIMARY mongo:27017
ENV MONGO_PRIMARY ${MONGO_PRIMARY}

ENV ME_CONFIG_MONGODB_SERVER ${MONGO_PRIMARY},mongo2,mongo3
ENV ME_CONFIG_MONGODB_URL mongodb://${MONGO_PRIMARY},mongo2:27017,mongo3:27017/

EXPOSE 8081